# Generated by Django 3.2.6 on 2021-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squared_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squared',
            name='done',
            field=models.BooleanField(default='0'),
        ),
    ]
