# Generated by Django 3.2.6 on 2021-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squared_app', '0002_alter_squared_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squared',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
